name: Run

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest
    environment: Actions
    steps:
    - uses: actions/checkout@main
    - name: Run
      uses: coactions/setup-xvfb@main
      env: 
        CONF: ${{ secrets.CONF }}
      with:
        run: dotnet run
